### ISSUE TITLE
[Feature Request] Add support for spot instances

### ISSUE THREAD

**Issue by yongzhang** [alibabacloud-automation/terraform-alicloud-autoscaling#7]
Hi

Can you please add support to mix on-demand and spot instances, as there're already args like `on_demand_base_capacity`, `on_demand_percentage_above_base_capacity `, `spot_instance_pools `, `spot_instance_remedy` ... in https://www.terraform.io/docs/providers/alicloud/r/ess_scaling_group.html.
Thanks.

**Comment by xiaozhu36** [comment]
HI  @yongzhang Thanks for your feedback and the release 1.5.0 has supported them. Please check it.

**Comment by yongzhang** [comment]
@xiaozhu36 Thanks!
